### ISSUE TITLE
HDF5ExtError: HDF5 error back trace

### ISSUE THREAD

**Issue by Ben-Yee** [Ming-er/NeuralNILM_Pytorch#2]
I got an error like this：
`SGN
Started training for  SGN
Joint training for  SGN
............... Loading Data for training ...................
Loading data for  ukdale  dataset
---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
<ipython-input-2-a6442bd2b867> in <module>
     43 }
     44 
---> 45 API(e)

G:\Code\NeuralNILM_Pytorch-main\nilmtk\api.py in __init__(self, params)
     48         self.artificial_aggregate = params.get('artificial_aggregate',self.artificial_aggregate)
     49         self.chunk_size = params.get('chunk_size',self.chunk_size)
---> 50         self.experiment(params)
     51 
     52     def experiment(self,params):

G:\Code\NeuralNILM_Pytorch-main\nilmtk\api.py in experiment(self, params)
     66 
     67             print("Joint training for ",clf.MODEL_NAME)
---> 68             self.train_jointly(clf,d)
     69             print("Finished training for ",clf.MODEL_NAME)
     70 

G:\Code\NeuralNILM_Pytorch-main\nilmtk\api.py in train_jointly(self, clf, d)
     83         for dataset in d:
     84             print("Loading data for ",dataset, " dataset")
---> 85             train = DataSet(d[dataset]['path'])
     86             for building in d[dataset]['buildings']:
     87                 print("Loading building ... ",building)

G:\Code\NeuralNILM_Pytorch-main\nilmtk\dataset.py in __init__(self, filename, format)
     42         self.metadata = {}
     43         if filename is not None:
---> 44             self.import_metadata(get_datastore(filename, format))
     45 
     46     def import_metadata(self, store):

G:\Code\NeuralNILM_Pytorch-main\nilmtk\utils.py in get_datastore(filename, format, mode)
    315     if filename is not None:
    316         if format == 'HDF':
--> 317             return HDFDataStore(filename, mode)
    318         elif format == 'CSV':
    319             return CSVDataStore(filename)

G:\Code\NeuralNILM_Pytorch-main\nilmtk\docinherit.py in f(*args, **kwargs)
     44         @wraps(self.mthd, assigned=('__name__', '__module__'))
     45         def f(*args, **kwargs):
---> 46             return self.mthd(obj, *args, **kwargs)
     47 
     48         return self.use_parent_doc(f, overridden)

G:\Code\NeuralNILM_Pytorch-main\nilmtk\datastore\hdfdatastore.py in __init__(self, filename, mode)
     22             warnings.filterwarnings('ignore', category=RuntimeWarning, message='.*numpy.ufunc size changed.*')
     23 
---> 24             self.store = pd.HDFStore(filename, mode, complevel=9, complib='blosc')
     25             super(HDFDataStore, self).__init__()
     26 

E:\ProgramData\Anaconda3\envs\NeuralNILM\lib\site-packages\pandas\io\pytables.py in __init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
    503         self._fletcher32 = fletcher32
    504         self._filters = None
--> 505         self.open(mode=mode, **kwargs)
    506 
    507     def __fspath__(self):

E:\ProgramData\Anaconda3\envs\NeuralNILM\lib\site-packages\pandas\io\pytables.py in open(self, mode, **kwargs)
    625 
    626         try:
--> 627             self._handle = tables.open_file(self._path, self._mode, **kwargs)
    628         except (IOError) as e:  # pragma: no cover
    629             if "can not be written" in str(e):

E:\ProgramData\Anaconda3\envs\NeuralNILM\lib\site-packages\tables\file.py in open_file(filename, mode, title, root_uep, filters, **kwargs)
    313 
    314     # Finally, create the File instance, and return it
--> 315     return File(filename, mode, title, root_uep, filters, **kwargs)
    316 
    317 

E:\ProgramData\Anaconda3\envs\NeuralNILM\lib\site-packages\tables\file.py in __init__(self, filename, mode, title, root_uep, filters, **kwargs)
    776 
    777         # Now, it is time to initialize the File extension
--> 778         self._g_new(filename, mode, **params)
    779 
    780         # Check filters and set PyTables format version for new files.

tables\hdf5extension.pyx in tables.hdf5extension.File._g_new()

HDF5ExtError: HDF5 error back trace

  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5F.c", line 509, in H5Fopen
    unable to open file
  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5Fint.c", line 1498, in H5F_open
    unable to open file: time = Fri Oct 22 16:17:09 2021
, name = 'G:\迅雷下载\非侵入式载荷识别\DataSet\UKDALE\UK-DALE-2015\ukdale.h5', tent_flags = 1
  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5FD.c", line 734, in H5FD_open
    open failed
  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5FDsec2.c", line 346, in H5FD_sec2_open
    unable to open file: name = 'G:\迅雷下载\非侵入式载荷识别\DataSet\UKDALE\UK-DALE-2015\ukdale.h5', errno = 2, error message = 'No such file or directory', flags = 1, o_flags = 2

End of HDF5 error back trace

Unable to open/create file 'G:\迅雷下载\非侵入式载荷识别\DataSet\UKDALE\UK-DALE-2015\ukdale.h5'`

this is my first time to use this kind of format.But I dont know how to fix it.

**Comment by Ben-Yee** [comment]
I was running this on Windows, and I solved it by giving a correct 'path'
